# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'simple-webserver'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'

steps:
- script: echo Hello, James time to test your go!
  displayName: 'Greeting'

- task: GoTool@0
  inputs:
    version: '1.14.1'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(srcDirectory)'
- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(srcDirectory)'
