
trigger:
- master

resources:
- repo: self

variables:
- name: localImage
  value: 'local/simpleserver:$(Build.BuildId)'
- name: productionImage
  value: 'jpetersenames/simpleserver:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        DOCKER_BUILDKIT=1 docker build -t $(localImage) -f Dockerfile .
    - script: python -m pip install --upgrade setuptools wheel anchorecli
      displayName: Install Anchore CLI

    - script: |
        curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- \
          scan -b .anchore/policy.json -d Dockerfile -f -r $(localImage)
      displayName: Anchore Security Scan

    - script: |
        docker tag $(localImage) $(productionImage)
      displayName: Tag the image as production

    - task: Docker@2
      displayName: Push the image to the production registry
      inputs:
        command: push
        repository: jpetersenames/simpleserver
        dockerfile: Dockerfile
        containerRegistry: production
        tags: |
          $(Build.BuildId)


