# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistry: 'jpetersenames/simple-webserver'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'
  tag: $(Build.SourceVersion)
  dockerRegistryServiceConnection: 'jpetersenames-dockerhub'
  image: docker.io/library/debian:7


# steps:
stages:
- stage: Golang
  displayName: CI for Go
  jobs:
  - job: Golang
    displayName: Build and Test Go
    steps:
    - task: GoTool@0
      inputs:
        version: '1.14.1'

    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(srcDirectory)'

    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v'
        workingDirectory: '$(srcDirectory)'


- stage: Docker
  displayName: Build and Push Docker
  jobs:
  - job: Docker
    displayName: Build and Push Docker
    steps:
    - task: Docker@2
      displayName: Build the simple-webserver image
      inputs:
        command: buildAndPush
        dockerfile: Dockerfile
        repository: $(dockerRegistry)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - script: |
        docker image ls
      displayName: Listing images

- stage: Anchore
  displayName: Anchore Security Scan
  jobs:
  - job: Anchore
    displayName: Anchore Security Scan
    steps:
    - script: python -m pip install --upgrade pip setuptools wheel
      displayName: Install tools for Anchore CLI

    - script: |
        pip install --upgrade anchorecli
        export "PATH=$PATH:/home/vsts/.local/bin"
        export "ANCHORE_CLI_USER=admin"
        export "ANCHORE_CLI_PASS=foobar"
        export "ANCHORE_CLI_URL=http://anchore-testjp.eastus.cloudapp.azure.com:8228/v1"
      displayName: Configure Anchore Security Scan

    - script: |
        anchore-cli image add "$(image)"
        # anchore-cli image add "$(dockerRegistry):$(tag)" --dockerfile=Dockerfile
      displayName: Add image

    - script: |
        anchore-cli image wait "$(image)"
      displayName: Wait for image

    - script: |
        anchore-cli image content "$(image)" os
      displayName: List content of image

    - script: |
        anchore-cli image vuln "$(image)" all
      displayName: List vulnerabilities in image

    - script: |
        anchore-cli evaluate check "$(image)"
      displayName: Evaluate image
