# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'simple-webserver'
  srcDirectory: '$(System.DefaultWorkingDirectory)/src'
  tag: $(Build.SourceVersion)

steps:
- script: echo Hello, James time to test your go!
  displayName: 'Greeting'

- task: GoTool@0
  inputs:
    version: '1.14.1'

- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(srcDirectory)'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(srcDirectory)'

- task: Docker@2
  displayName: Build the simple-webserver image
  inputs:
    repository: $(imageName)
    command: build
    dockerfile: Dockerfile
    tags: |
      $(tag)

- script: |
    docker image ls
  displayName: Listing images

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: Install tools for Anchore CLI

- script: |
    pip install anchorecli
    export "ANCHORE_CLI_USER=admin"
    export "ANCHORE_CLI_PASS=foobar"
    export "ANCHORE_CLI_URL=http://anchore-testjp.eastus.cloudapp.azure.com:8228/v1"
    anchore-cli system status
  displayName: Anchore Security Scan
